### ISSUE TITLE
Mod menu

### ISSUE THREAD

**Issue by ZetaReserX** [JartanFTW/kot-skipper#29]
It should have the following functions:
player teleport,
speed change,
immortality,
auto search for gems,
turn off traps and collisions,
game acceleration

**Comment by ZetaReserX** [comment]
and increase or decrease the size of the hitbox

**Comment by JartanFTW** [comment]
Unfortunately this is very far out of scope for this program, sorry.
I'm not interested in making any explicit hacks, sorry.
