### ISSUE TITLE
WinError 10061

### ISSUE THREAD

**Issue by ZetaReserX** [JartanFTW/kot-skipper#33]
how to fix WinError 10061

**Comment by JartanFTW** [comment]
What was the solution?

**Comment by ZetaReserX** [comment]
You need to change the port in game.py in the new version of bluestasks, the port changes every time you run the emulator

**Comment by ZetaReserX** [comment]
How can I use my rtx 3060 ti to speed up the process of finding gems??

**Comment by JartanFTW** [comment]
> You need to change the port in game.py in the new version of bluestasks, the port changes every time you run the emulator

Interesting. This does not occur to me. I'll take a look when I find the time.

**Comment by JartanFTW** [comment]
> How can I use my rtx 3060 ti to speed up the process of finding gems??

You can't. I haven't programmed it in. The speed difference between using a CPU versus a GPU on a neural network of this size is so small that it's not even worth implementing. You would see basically no difference.

The primary factor limiting the speed of this tool is the transition time when skipping dungeons. An artificial delay is implemented here, so it can take screenshot(s) accurately.
